name: 'IAC Terraform'

on: [workflow_dispatch]

permissions:
  contents: read
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Clone sre-terraform-modules
      uses: actions/checkout@v3
      with:
        repository: rockcontent/sre-terraform-modules
        path: .iac/terraform
        ref: dev-ecs
        token: ${{ secrets.TOKEN_sre_terraform_github }}

    - name: Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init Dev
      run: |
        cd .iac
        for i in $(`cat *common.var`); do
            export $i
            echo `\'$i\'` >> $GITHUB_ENV
        done
        if [ ${{ github.ref_name }} == "dev" ]; then 
          for i in $(cat *-dev.var); do
            export $i
            echo `\'$i\'` >> $GITHUB_ENV
          done
        fi
        if [ ${{ github.ref_name }} == "prod" ]; then 
          for i in $(`cat *-prod.var`); do
            export $i
            echo `\'$i\'` >> $GITHUB_ENV
          done
        fi
        #
        terraform --version
        terraform init \
          --backend-config="key=${{ github.event.repository.name }}-${{ github.ref_name }}/terraform.tfstate" \
          --backend-config="bucket=$TFBUCKETSTATE" \
          --backend-config="region=$AWS_REGION"
        terraform validate
        terraform plan -out=tfplanfile
        terraform apply -input=false "tfplanfile"



